name: emulator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6-146.2.beta <3.0.0'

dependencies: 
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  intl: ^0.17.0
  ini: ^2.1.0
  google_fonts: ^3.0.1
  tcp_socket_connection: ^0.3.1
  grpc: ^3.0.2
  protoc_plugin: ^20.0.0
  shimmer: ^2.0.0

  camera_platform_interface: ^2.3.2
  camera: ^0.10.3
  # camera_windows: ^0.2.1+3

  syncfusion_flutter_sliders: ^20.4.44
  syncfusion_flutter_gauges: ^20.4.44
  syncfusion_flutter_charts: ^20.4.44

  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  flutter_secure_storage: ^7.0.1
  shared_preferences: ^2.0.17
  hive_flutter: ^1.1.0

  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  flutter_map_location_marker: ^5.2.0+2



  flutter_compass: ^0.7.0
  permission_handler: ^10.2.0
  sensors_plus: ^2.0.1
  battery_plus: ^3.0.0
  battery_info: ^1.1.1 
  # audioplayers: ^3.0.1
  # flutter_audio_streaming: ^1.0.5
  mic_stream: ^0.6.4

  path_provider: ^2.0.12
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0

  record: ^4.4.4
  flutter_beacon: ^0.5.1
  # beacons_plugin: ^2.0.8
  beacon_broadcast: ^0.3.1
  flutter_blue: ^0.8.0

  
  
  


  # flutter_staggered_grid_view: ^0.6.2
  # flutter_staggered_animations: ^1.1.1
         

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  generate: true
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # ICON GENERATING COMMANDS:
  # flutter pub get
  # flutter pub run flutter_launcher_icons:main

  # GENERATING PROTOC FILES:
  # protoc --dart_out=grpc:lib/src/generated/socket -Iprotocs protocs/socket.proto

